### ISSUE TITLE
Plants destroyed by one side of vehicle

### ISSUE THREAD

**Issue by Dzi4d3k** [DeckerMMIV/FarmSim_Mod_WheelLanes#2]
As in subject we observe that vehicles tend to destroy plants only by one side at a time. I don't know if this is map specific as we use 4x map.
We will do another tests on 1x map.

**Comment by DeckerMMIV** [comment]
The x4 map could be an issue, if the density file(s) is not of enough "high-resolution".

Another problem could be, if the vehicle(s) have "invisible wheels", that are referenced in the vehicle XML file's `<wheels>` section

**Comment by Dzi4d3k** [comment]
Density files have resolution 8192x8192, I supposed that is enough high for x4 map, if map x1 has 4096x4096 dimensions for its density files.
For second though I'll check results per vehicle.

**Comment by Dzi4d3k** [comment]
Looks like resolution on issue #4 resolved this issue. Now wheel lines looks, and work like in 0.7 version.
