### ISSUE TITLE
Exception for Alfalfa/lucerne 

### ISSUE THREAD

**Issue by SoloTwo** [DeckerMMIV/FarmSim_Mod_WheelLanes#3]
Any way to add a line for reducing lucerne to growth level 1 or 2 instead of completely destroying it?  Would be extremely helpful since you can harvest it continuously.  I managed to change the grass effect to the 2nd growth stage for a bit more realism but I'm not exactly sure how to add lucerne to the code.

**Comment by Dzi4d3k** [comment]
Wow, I was going to open exact the same discussion on grass, cause I totally agree that grass shouldn't be destroyed completely as in real driving occasionally on meadow doesn't make such damage.
Second question is almost similar situation.

**Comment by DeckerMMIV** [comment]
What fruit-/fill-type name(s) does lucerne has in-game?
Is it `FILLTYPE_LUCERNE`, `FILLTYPE_ALFALFA` and/or something else?

@Dzi4d3k - 'Grass' isn't destroyed completely. It is only set back to the first growth-state, i.e. "just seeded". But I can see that it may probably be more "visually realistic" to set it to the second growth-state.

**Comment by DeckerMMIV** [comment]
I've added some stuff to v0.9.0-BETA - take a look and please report back if it works or not.

**Comment by SoloTwo** [comment]
Works awesome on grass Decker, don't have any lucerne currently to test on it but guessing it works the same as grass by looking at the lua.  Thanks a lot. :+1:
