### ISSUE TITLE
Typos in code?

### ISSUE THREAD

**Issue by Dzi4d3k** [DeckerMMIV/FarmSim_Mod_WheelLanes#4]
Hello,

Being curious I was comparing differences between version 0.8 and 0.9, and found lines:
133 and 158 with following code
 `area.sx,area.sz, area.wz,area.wz, area.hx,area.hz, -- destination parallelogram`

aren't `area.wz` typed twice, where first one should be (I suppose) `area.wx`, comparing to old:

`area.x, area.z, area.widthX, area.widthZ, area.heightX, area.heightZ, -- destination parallelogram`

Just asking.

**Comment by DeckerMMIV** [comment]
Oops. Yes you are correct. - Making a fix.

**Comment by Dzi4d3k** [comment]
Thank you for confirmation and correction.
