### ISSUE TITLE
Removing the grass

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [DeckerMMIV/FarmSim_Mod_WheelLanes#6]
In reality, if the tractor passing through the grass, the grass does not disappear, it can mow. May make an exception - to remain minimal grass roll after passing through it. This can be done for wheat and barley.

**Comment by sootysax** [comment]
See #5 - i was able to modify wheel lanes to do just that.

**Comment by Gonimy-Vetrom** [comment]
Yes, we are talking about one and the same.

**Comment by DeckerMMIV** [comment]
The 'grass' foliage-layer has only 4 growth-states (values 1 to 4), so I would be hard pressed to change the current "reduce grass" when wheels drive over it.

Currently in [source line 108](https://github.com/DeckerMMIV/FarmSim_Mod_WheelLanes/blob/master/WheelLanes/WheelLanes.lua#L108) it is set, so if the 'grass' growth-state is at minimum 3 and maximum 7, then it will be reduced to growth-state 2 (`value=2`).

So in essence, it is "_remain minimal grass after passing through it._"

Or are you asking for, that the "minimal grass" should be able to be mowed/cutted?
