### ISSUE TITLE
PiQup does not destroy crops.

### ISSUE THREAD

**Issue by Stowed4Sea** [DeckerMMIV/FarmSim_Mod_WheelLanes#7]
I'm running a dedicated server with WheelLanes active and it seems to work for the combines and other tractors I've tried, but the PiQup does not destroy any crops.  

It should be noted that at the time of finding this out, sunflowers was the only field that was above growth stage 2 to test on, so I could not verify problem against other crops.

**Comment by DeckerMMIV** [comment]
There is a check so only physical wheels with a radius of greater than 0.5 will be able to destroy crops.

This to prevent equipment, which possibly contains hidden and/or many physical wheels, to destroy too much.

The PiQup have smaller physical wheels, according to its piQup.xml vehicle xml file:

```
<vehicle type="carDynamicMountAttacher">
    <annotation>Copyright (C) GIANTS Software GmbH, All Rights Reserved.</annotation>
    <name>
        <en>PiQup</en>
        <de>PiQup</de>
    </name>
...
    <wheels autoRotateBackSpeed="1.5">
        <wheel ... radius="0.43" ...
        <wheel ... radius="0.43" ...
        <wheel ... radius="0.43" ...
        <wheel ... radius="0.43" ...
    </wheels>
...
```

**Comment by Stowed4Sea** [comment]
I see, it makes sense now.  Thanks
